<DetailScreen>:
    
    BoxLayout:
        id:mbox
        size_hint:.8,.8
        pos_hint:{"center_x":.5,"center_y":.5}
        spacing: dp(50)
        orientation:'vertical'
        Image:
            id: imageView
            source: 'cat-3.jpg'
            allow_stretch: True
            width: 200
            size_hint_y: None
        
         
                 
        

    